#!/usr/bin/env python3
"""
PyMOL Interface Calculator
Calculate the center of mass for the GPR55/G-alpha interface
Run this script in PyMOL console or as external script

Usage in PyMOL:
  run pymol_interface_calculator.py
  calculate_interface_center()
"""

from pymol import cmd
import numpy as np


def calculate_interface_center(chain_r="R", chain_a="A", cutoff=5.0):
    """
    Calculate the center of mass of the interface between two protein chains.
    
    Parameters:
    - chain_r: First chain (e.g., GPR55 receptor) - default "R"
    - chain_a: Second chain (e.g., G-alpha subunit) - default "A"
    - cutoff: Distance cutoff for interface residues in Angstroms - default 5.0
    
    Returns:
    - Dictionary with interface coordinates and statistics
    """
    
    # Select interface residues
    cmd.select("interface_chain1", f"chain {chain_r} and (byres chain {chain_a} around {cutoff})")
    cmd.select("interface_chain2", f"chain {chain_a} and (byres chain {chain_r} around {cutoff})")
    
    # Get atom counts
    atoms_chain1 = cmd.count_atoms("interface_chain1")
    atoms_chain2 = cmd.count_atoms("interface_chain2")
    
    print(f"\n{'='*60}")
    print(f"GPR55/G-alpha Interface Analysis")
    print(f"{'='*60}")
    print(f"Chain {chain_r} interface atoms: {atoms_chain1}")
    print(f"Chain {chain_a} interface atoms: {atoms_chain2}")
    print(f"Total interface atoms: {atoms_chain1 + atoms_chain2}")
    
    # Get coordinates
    coords_chain1 = cmd.get_coords("interface_chain1")
    coords_chain2 = cmd.get_coords("interface_chain2")
    
    if coords_chain1 is None or coords_chain2 is None:
        print("Error: Could not get coordinates. Make sure structure is loaded.")
        return None
    
    # Calculate center of mass
    all_coords = np.vstack([coords_chain1, coords_chain2])
    center = np.mean(all_coords, axis=0)
    
    print(f"\nInterface Center of Mass:")
    print(f"  X: {center[0]:.3f}")
    print(f"  Y: {center[1]:.3f}")
    print(f"  Z: {center[2]:.3f}")
    
    # Create pseudoatom at interface center
    cmd.pseudoatom("interface_center", pos=list(center))
    cmd.show("spheres", "interface_center")
    cmd.set("sphere_scale", 2.0, "interface_center")
    cmd.color("hotpink", "interface_center")
    
    # Visualize interface
    cmd.show("sticks", "interface_chain1")
    cmd.show("sticks", "interface_chain2")
    cmd.color("blue", "interface_chain1")
    cmd.color("chartreuse", "interface_chain2")
    
    print(f"\n{'='*60}")
    print("Visualization created:")
    print("  - Blue sticks: GPR55 interface residues")
    print("  - Green sticks: G-alpha interface residues")
    print("  - Pink sphere: Interface center")
    print(f"{'='*60}")
    
    # Return for script use
    result = {
        'center_x': center[0],
        'center_y': center[1],
        'center_z': center[2],
        'chain1_atoms': atoms_chain1,
        'chain2_atoms': atoms_chain2,
        'total_atoms': atoms_chain1 + atoms_chain2,
        'cutoff': cutoff
    }
    
    return result


def generate_vina_config(center, box_size=25, output_file="conf_interface.txt"):
    """
    Generate a Vina configuration file for the interface site.
    
    Parameters:
    - center: Dictionary with center_x, center_y, center_z
    - box_size: Grid box size in Angstroms
    - output_file: Path to output config file
    """
    
    config_template = f"""# Vina Configuration file for GPR55/G-alpha Interface
# Generated by PyMOL Interface Calculator
# Calculated from centerofmass of interface residues

receptor = GPR55_complex.pdbqt

# Interface Center of Mass
center_x = {center['center_x']:.3f}
center_y = {center['center_y']:.3f}
center_z = {center['center_z']:.3f}

# Grid box size
size_x = {box_size}
size_y = {box_size}
size_z = {box_size}

# Search parameters
exhaustiveness = 16

# Interface statistics:
# Chain R atoms: {center['chain1_atoms']}
# Chain A atoms: {center['chain2_atoms']}
# Cutoff: {center['cutoff']} Angstroms
"""
    
    with open(output_file, 'w') as f:
        f.write(config_template)
    
    print(f"\nVina config saved to: {output_file}")


# Extension of PyMOL commands
cmd.extend("calculate_interface_center", calculate_interface_center)

# If running as standalone script
if __name__ == "__main__":
    print("PyMOL Interface Calculator loaded.")
    print("Usage in PyMOL:")
    print("  calculate_interface_center(chain_r='R', chain_a='A', cutoff=5.0)")
